apiVersion: v1
kind: Secret
metadata:
  name: ootb-supply-chain-testing-scanning-remove-image-to-url
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: "ootb-supply-chain-testing-scanning-install-overlays"
type: Opaque
stringData:
  remove-image-to-url.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"metadata":{"name":"scanning-image-scan-to-url"}, "kind": "ClusterSupplyChain"})
    #@overlay/remove
    ---