apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: ootb-supply-chain-testing-tap-install
    kapp.k14s.io/change-group: "ootb-supply-chain-testing-install-rbac"
  name: ootb-supply-chain-testing-tap-install-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: ootb-supply-chain-testing-tap-install
    kapp.k14s.io/change-group: "ootb-supply-chain-testing-install-rbac"
  name: ootb-supply-chain-testing-tap-install-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ootb-supply-chain-testing-tap-install-cluster-role
subjects:
- kind: ServiceAccount
  name: ootb-supply-chain-testing-tap-install-sa
  namespace: tap-install
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: ootb-supply-chain-testing-tap-install
    kapp.k14s.io/change-group: "ootb-supply-chain-testing-install-rbac"
  name: ootb-supply-chain-testing-tap-install-sa
  namespace: tap-install