apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: password-editor
rules:
- apiGroups:
  - secretgen.k14s.io
  resources:
  - passwords
  verbs:
  - get
  - list
  - create
  - delete
  - deletecollection
  - patch
  - update