apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: rbac-mgmt
  namespace: kapp
  annotations:
    kapp.k14s.io/change-group: "{name}"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting tap-install"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting tap-install"
spec:
  serviceAccountName: kapp
  fetch:
  - imgpkgBundle:
      image: ghcr.io/making/rbac-mgmt-bundle:0.0.1
  - git:
      url: https://github.com/tanzu-japan/jaguchi-manifests.git
      ref: origin/main
  syncPeriod: 1m
  template:
  - ytt:
      paths:
      - 0/config
      - 0/schema.yaml
      valuesFrom:
      - path: 1/jaguchi/config/platform/rbac-mgmt/rbac-mgmt-data-values.yaml
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=true
      inspect:
        rawOptions:
        - --tree=true